/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views;

import Views.Tour.*;
import Views.DonHang.*;
import Views.KhachHang.*;
import javax.swing.*;
/**
 *
 * @author CanhDev
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        TourBtn = new javax.swing.JButton();
        OrderBtn = new javax.swing.JButton();
        ClientBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản lý tour du lịch - công ty VN-booking");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipadx = 320;
        gridBagConstraints.ipady = 26;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 0, 0, 0);
        getContentPane().add(jLabel1, gridBagConstraints);

        TourBtn.setBackground(new java.awt.Color(204, 204, 255));
        TourBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        TourBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/login/icon/9044989_password_icon.png"))); // NOI18N
        TourBtn.setText("Quản lý tour");
        TourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TourBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 12, 70, 0);
        getContentPane().add(TourBtn, gridBagConstraints);

        OrderBtn.setBackground(new java.awt.Color(204, 204, 255));
        OrderBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        OrderBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/login/icon/9044989_password_icon.png"))); // NOI18N
        OrderBtn.setText("Quản lý đơn hàng");
        OrderBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrderBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 50, 70, 0);
        getContentPane().add(OrderBtn, gridBagConstraints);

        ClientBtn.setBackground(new java.awt.Color(204, 204, 255));
        ClientBtn.setFont(new java.awt.Font("Segoe UI", 3, 16)); // NOI18N
        ClientBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Views/login/icon/9044989_password_icon.png"))); // NOI18N
        ClientBtn.setText("Quản lý khách hàng");
        ClientBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(86, 37, 70, 0);
        getContentPane().add(ClientBtn, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TourBtnActionPerformed
        QuanLyTour QuanLyTourForm = new QuanLyTour();
        QuanLyTourForm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        QuanLyTourForm.setVisible(true);
    }//GEN-LAST:event_TourBtnActionPerformed

    private void OrderBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrderBtnActionPerformed
        QuanLyDonHang QuanLyDonHangForm = new QuanLyDonHang();
        QuanLyDonHangForm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        QuanLyDonHangForm.setVisible(true);
    }//GEN-LAST:event_OrderBtnActionPerformed

    private void ClientBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientBtnActionPerformed
        QuanLyKhachHang QuanLyKhachHangForm = new QuanLyKhachHang();
        QuanLyKhachHangForm.setDefaultCloseOperation(JFrame.HIDE_ON_CLOSE);
        QuanLyKhachHangForm.setVisible(true);
    }//GEN-LAST:event_ClientBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClientBtn;
    private javax.swing.JButton OrderBtn;
    private javax.swing.JButton TourBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
