/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.DonHang;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashSet;
import javax.swing.JOptionPane;
import Models.*;

/**
 *
 * @author HI
 */
public class SuaDonHang extends javax.swing.JDialog {

    /**
     * Creates new form SuaDonHang
     */
    private QuanLyDonHang quanLyDonHang;

    public SuaDonHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        quanLyDonHang = (QuanLyDonHang) parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDonHang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtSoNgayDuLich = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnXacNhanSua = new javax.swing.JButton();
        btnHuySua = new javax.swing.JButton();
        txtMaDonHang = new javax.swing.JLabel();
        txtMaTour = new javax.swing.JLabel();
        txtMaKhachHang = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SỬA THÔNG TIN ĐƠN HÀNG");

        jLabel2.setText("Mã đơn hàng: ");

        jLabel3.setText("Tên đơn hàng: ");

        jLabel4.setText("Ngày lập: ");

        jLabel5.setText("Số ngày du lịch: ");

        jLabel6.setText("Mã tour: ");

        jLabel7.setText("Mã khách hàng: ");

        btnXacNhanSua.setText("Xác nhận");
        btnXacNhanSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanSuaActionPerformed(evt);
            }
        });

        btnHuySua.setText("Hủy");
        btnHuySua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuySuaActionPerformed(evt);
            }
        });

        txtMaDonHang.setText("jLabel8");

        txtMaTour.setText("jLabel8");

        txtMaKhachHang.setText("jLabel8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(55, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(34, 34, 34)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTenDonHang)
                                            .addComponent(txtMaDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                                            .addComponent(txtMaTour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNgayLap)
                                    .addComponent(txtSoNgayDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnXacNhanSua)
                        .addGap(67, 67, 67)
                        .addComponent(btnHuySua)
                        .addGap(116, 116, 116))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtMaDonHang))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTenDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtMaTour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtMaKhachHang))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSoNgayDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXacNhanSua)
                    .addComponent(btnHuySua))
                .addContainerGap(141, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanSuaActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        String maDonHang, tenDonHang, maTour, maKhachHang;
        int soNgayDuLich = 0;
        LocalDate ngayLap = null;
        boolean isOK = true;
        Tour tour = new Tour();
        KhachHang khachHang = new KhachHang();
        maDonHang = txtMaDonHang.getText().trim();
        tenDonHang = txtTenDonHang.getText().trim();
        maTour = txtMaTour.getText().trim();
        maKhachHang = txtMaKhachHang.getText().trim();

        if (maDonHang.isEmpty() || tenDonHang.isEmpty() || maTour.isEmpty() || maKhachHang.isEmpty()
                || txtNgayLap.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin!");
            isOK = false;
        }

        if (isOK == true && !tenDonHang.matches("^[\\p{L}\\d\\s]*$")) {
            JOptionPane.showMessageDialog(rootPane, "Tên không được chứa kí tự số và các kí tự đặc biệt!");
            isOK = false;
        }

        if (isOK == true) {
            try {
                soNgayDuLich = Integer.parseInt(txtSoNgayDuLich.getText().trim());
                if (soNgayDuLich <= 0) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số ngày du lịch phải là số nguyên dương!");
                isOK = false;
            }
        }

        if (isOK == true) {
            try {
                ngayLap = LocalDate.parse(txtNgayLap.getText().trim(), dateFormatter);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ngày lập không hợp lệ!");
                isOK = false;
            }
        }
        tour = quanLyDonHang.timTourTheoMa(maTour, quanLyDonHang.getDSTour());
        khachHang = quanLyDonHang.timKhachHangTheoMa(maKhachHang, quanLyDonHang.getDSKhachHang());  
//        try {
//            if (isOK == true && !maTour.matches("^[a-zA-Z0-9]+$")) {
//                JOptionPane.showMessageDialog(rootPane, "Mã tour chứa ký tự không hợp lệ!");
//                isOK = false;
//            } else {
//                tour = quanLyDonHang.timTourTheoMa(maTour, quanLyDonHang.getDSTour());
//                if (isOK == true && tour == null) {
//                    JOptionPane.showMessageDialog(rootPane, "Mã tour không tồn tại trong dữ liệu!");
//                    isOK = false;
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong việc truy cập dữ liệu!");
//            isOK = false;
//        }
//        try {
//            if (isOK == true && !maKhachHang.matches("^[a-zA-Z0-9]+$")) {
//                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng chứa ký tự không hợp lệ!");
//                isOK = false;
//            } else {
//                khachHang = quanLyDonHang.timKhachHangTheoMa(maKhachHang, quanLyDonHang.getDSKhachHang());
//                if (isOK == true && khachHang == null) {
//                    JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không tồn tại trong dữ liệu!");
//                    isOK = false;
//                }
//            }
//        } catch (Exception e) {
//            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong việc truy cập dữ liệu!");
//            isOK = false;
//        }
        if (isOK) {
            DonHang donHang = new DonHang(maDonHang, tenDonHang, ngayLap, soNgayDuLich, tour, khachHang);

            quanLyDonHang.updateDonHang(donHang);
            JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công!");
            this.dispose();
        }

    }//GEN-LAST:event_btnXacNhanSuaActionPerformed

    private void btnHuySuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuySuaActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuySuaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaDonHang dialog = new SuaDonHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    public void setEditData(DonHang donHang) {
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        txtMaDonHang.setText(donHang.getMaDonHang());
        txtTenDonHang.setText(donHang.getTenDonHang());
        txtNgayLap.setText(donHang.getNgayLap().format(dateFormatter));
        txtSoNgayDuLich.setText(String.valueOf(donHang.getSoNgayDuLich()));
        txtMaKhachHang.setText(donHang.getKhachhang().getMaKhachHang());
        txtMaTour.setText(donHang.getTour().getMaTour());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuySua;
    private javax.swing.JButton btnXacNhanSua;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel txtMaDonHang;
    private javax.swing.JLabel txtMaKhachHang;
    private javax.swing.JLabel txtMaTour;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoNgayDuLich;
    private javax.swing.JTextField txtTenDonHang;
    // End of variables declaration//GEN-END:variables
}
