/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Views.DonHang;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import Models.*;
import java.util.*;
import Controllers.DonHang.*;
import javax.swing.*;
/**
 *
 * @author HI
 */
public class ThemDonHang extends javax.swing.JDialog {

    private ArrayList<String> IdTours = new ArrayList<>();
    private ArrayList<String> IdKhachHangs = new ArrayList<>();
    private LinkedHashSet<Tour> dsTour = new LinkedHashSet<>();
    private LinkedHashSet<KhachHang> dsKH = new LinkedHashSet<>();
    private ControllerDonHang controllerDH = new ControllerDonHang();
    //
    private QuanLyDonHang quanLyDonHang;

    public ThemDonHang(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        quanLyDonHang = (QuanLyDonHang) parent;
        
        //
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        btnXacNhan = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtMaDonHang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtTenDonHang = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtNgayLap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtSoNgayDuLich = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        tbnXacNhanThem = new javax.swing.JButton();
        btnHuyThem = new javax.swing.JButton();
        dsTour = (LinkedHashSet<Tour>) controllerDH.readDataFromeFile("Tour_List.txt");
        for(Tour t : dsTour){
            IdTours.add(t.getMaTour());
        }
        DefaultComboBoxModel<String> idToursModel = new DefaultComboBoxModel<>();

        for (String idTour : IdTours) {
            idToursModel.addElement(idTour);
        }
        txtMaTour = new javax.swing.JComboBox<>();
        dsKH = (LinkedHashSet<KhachHang>) controllerDH.readDataFromeFile("QLKhachHang.txt");
        for(KhachHang t : dsKH){
            IdKhachHangs.add(t.getMaKhachHang());
        }
        DefaultComboBoxModel<String> idKhachHangsModel = new DefaultComboBoxModel<>();

        for (String idKhachHang : IdKhachHangs) {
            idKhachHangsModel.addElement(idKhachHang);
        }
        txtMaKhachHang = new javax.swing.JComboBox<>();

        jLabel2.setText("Mã đơn hàng: ");

        jLabel3.setText("Tên đơn hàng: ");

        jLabel4.setText("Ngày lập: ");

        jLabel5.setText("Số ngày du lịch: ");

        jLabel6.setText("Tour: ");

        jLabel7.setText("Khách hàng: ");

        btnXacNhan.setText("Xác nhận");
        btnXacNhan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXacNhanActionPerformed(evt);
            }
        });

        btnHuy.setText("Hủy");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Nhập thông tin");

        jLabel8.setText("Mã đơn hàng: ");

        jLabel9.setText("Tên đơn hàng: ");

        jLabel10.setText("Ngày lập: ");

        jLabel11.setText("Số ngày du lịch: ");

        jLabel12.setText("Mã tour: ");

        jLabel13.setText("Mã khách hàng: ");

        tbnXacNhanThem.setText("Xác nhận");
        tbnXacNhanThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnXacNhanThemActionPerformed(evt);
            }
        });

        btnHuyThem.setText("Hủy");
        btnHuyThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyThemActionPerformed(evt);
            }
        });

        txtMaTour.setModel(idToursModel);

        txtMaKhachHang.setModel(idKhachHangsModel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtSoNgayDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel12))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtMaDonHang)
                                    .addComponent(txtTenDonHang, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                                    .addComponent(txtMaTour, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtMaKhachHang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(tbnXacNhanThem)
                        .addGap(84, 84, 84)
                        .addComponent(btnHuyThem)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtMaDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtTenDonHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(txtMaTour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtMaKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtNgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtSoNgayDuLich, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHuyThem)
                    .addComponent(tbnXacNhanThem))
                .addGap(80, 80, 80))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnXacNhanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXacNhanActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnXacNhanActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyActionPerformed

    private void tbnXacNhanThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnXacNhanThemActionPerformed
        // TODO add your handling code here:
        DateTimeFormatter dateFormatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

        String maDonHang, tenDonHang, maTour, maKhachHang;
        int soNgayDuLich = 0;
        LocalDate ngayLap = null;
        boolean isOK = true;
        Tour tour = new Tour();
        KhachHang khachHang = new KhachHang();
        DonHang donHang = new DonHang();

        maDonHang = txtMaDonHang.getText().trim();
        tenDonHang = txtTenDonHang.getText().trim();
        maTour = txtMaTour.getSelectedItem().toString();
        maKhachHang = txtMaKhachHang.getSelectedItem().toString();

        if (maDonHang.isEmpty() || tenDonHang.isEmpty() || maTour.isEmpty() || maKhachHang.isEmpty()
                || txtNgayLap.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Vui lòng điền đầy đủ thông tin!");
            isOK = false;
        }

        try {
            if (isOK == true && !maDonHang.matches("^[a-zA-Z0-9]+$")) {
                JOptionPane.showMessageDialog(rootPane, "Mã đơn hàng chứa ký tự không hợp lệ!");
                isOK = false;
            } else {
                donHang = quanLyDonHang.timDonHangTheoMa(maDonHang, quanLyDonHang.getDSDonHang());
                if (isOK == true && donHang != null) {
                    JOptionPane.showMessageDialog(rootPane, "Mã đơn hàng đã tồn tại trong dữ liệu!");
                    isOK = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong việc truy cập dữ liệu!");
            isOK = false;
        }

        if (isOK == true && !tenDonHang.matches("^[\\p{L}\\d\\s]*$")) {
            JOptionPane.showMessageDialog(rootPane, "Tên không được chứa kí tự số và các kí tự đặc biệt!");
            isOK = false;
        }

        try {
            if (isOK == true && !maTour.matches("^[a-zA-Z0-9]+$")) {
                JOptionPane.showMessageDialog(rootPane, "Mã tour chứa ký tự không hợp lệ!");
                isOK = false;
            } else {
                tour = quanLyDonHang.timTourTheoMa(maTour, quanLyDonHang.getDSTour());
                if (isOK == true && tour == null) {
                    JOptionPane.showMessageDialog(rootPane, "Mã tour không tồn tại trong dữ liệu!");
                    isOK = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong việc truy cập dữ liệu!");
            isOK = false;
        }
        try {
            if (isOK == true && !maKhachHang.matches("^[a-zA-Z0-9]+$")) {
                JOptionPane.showMessageDialog(rootPane, "Mã khách hàng chứa ký tự không hợp lệ!");
                isOK = false;
            } else {
                khachHang = quanLyDonHang.timKhachHangTheoMa(maKhachHang, quanLyDonHang.getDSKhachHang());
                if (isOK == true && khachHang == null) {
                    JOptionPane.showMessageDialog(rootPane, "Mã khách hàng không tồn tại trong dữ liệu!");
                    isOK = false;
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Có lỗi trong việc truy cập dữ liệu!");
            isOK = false;
        }

        if (isOK == true) {
            try {
                ngayLap = LocalDate.parse(txtNgayLap.getText().trim(), dateFormatter);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Ngày lập không hợp lệ!");
                isOK = false;
            }
        }

        if (isOK == true) {
            try {
                soNgayDuLich = Integer.parseInt(txtSoNgayDuLich.getText().trim());
                if (soNgayDuLich <= 0) {
                    throw new NumberFormatException();
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(rootPane, "Số ngày du lịch phải là số nguyên dương!");
                isOK = false;
            }
        }

        //
        if (isOK) {
            DonHang donHangResult = new DonHang(maDonHang, tenDonHang, ngayLap, soNgayDuLich, tour, khachHang);

            quanLyDonHang.addDonHang(donHangResult);
            JOptionPane.showMessageDialog(rootPane, "Thêm thành công đơn hàng!");
        }
    }//GEN-LAST:event_tbnXacNhanThemActionPerformed

    private void btnHuyThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyThemActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnHuyThemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemDonHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThemDonHang dialog = new ThemDonHang(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHuy;
    private javax.swing.JButton btnHuyThem;
    private javax.swing.JButton btnXacNhan;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JButton tbnXacNhanThem;
    private javax.swing.JTextField txtMaDonHang;
    private javax.swing.JComboBox<String> txtMaKhachHang;
    private javax.swing.JComboBox<String> txtMaTour;
    private javax.swing.JTextField txtNgayLap;
    private javax.swing.JTextField txtSoNgayDuLich;
    private javax.swing.JTextField txtTenDonHang;
    // End of variables declaration//GEN-END:variables
}
