/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Views.Tour;
import Controllers.Tour.QuanLyTourController;
import Models.DonHang;
import Models.TableOfTour;
import Models.KhachHang;
import java.io.File;
import java.util.*;
import javax.swing.JOptionPane;
import Models.Tour;
import javax.swing.SwingConstants;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableCellRenderer;
import Controllers.DonHang.*;
import Views.Home;
/**
 *
 * @author CanhDev
 */

public class QuanLyTour extends javax.swing.JFrame {
    LinkedHashSet<Tour> dsTour=new LinkedHashSet<>();
    private LinkedHashSet<DonHang> dsDH = new LinkedHashSet<>();
    private ControllerDonHang controllerDH = new ControllerDonHang();
    int dongChon = -1;
    Tour t = new Tour();
    
    public void loadTableTour(){
        // Đường dẫn tới tệp tin cần kiểm tra
        String filePath = "Tour_List.txt";

        // Tạo đối tượng File
        File file = new File(filePath);
        //
        if (file.exists() && file.isFile()) {
            dsTour = (LinkedHashSet<Tour>)QuanLyTourController.readDataFromFile(filePath);
        }
        //
        QuanLyTourController.sortByPrice(dsTour, 0);
        TourTable.setModel(new TableOfTour(dsTour));
        setTableAlignmentCenter(TourTable);      
        setTableHeaderAlignmentCenter(TourTable);
        dsDH = (LinkedHashSet<DonHang>) controllerDH.readDataFromeFile("QLDonHang.txt");
    }
    public void loadTableTourBySortString(){
        TourTable.setModel(new TableOfTour(dsTour));
        setTableAlignmentCenter(TourTable);      
        setTableHeaderAlignmentCenter(TourTable);
    }
    public void loadTableTourBySearchString(LinkedHashSet<Tour> list){
        TourTable.setModel(new TableOfTour(list));
        setTableAlignmentCenter(TourTable);      
        setTableHeaderAlignmentCenter(TourTable);
    }
    public QuanLyTour() {
        //
        initComponents();
        loadTableTour();
        setLocationRelativeTo(null);
        dsDH = (LinkedHashSet<DonHang>) controllerDH.readDataFromeFile("QLDonHang.txt");
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TourTable = new javax.swing.JTable();
        AddBtnTour = new javax.swing.JButton();
        EditTourBtn = new javax.swing.JButton();
        DeleteBtnTour = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        IndexBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearchString = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        SortComboBox = new javax.swing.JComboBox<>();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Danh sách Tour");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        TourTable.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        TourTable.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        TourTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã Tour", "Tên Tour", "Giá tiền", "Địa điểm", "Đánh giá", "Lịch trình"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        TourTable.setRowMargin(4);
        TourTable.setShowGrid(true);
        jScrollPane1.setViewportView(TourTable);

        AddBtnTour.setBackground(new java.awt.Color(0, 153, 102));
        AddBtnTour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        AddBtnTour.setForeground(new java.awt.Color(0, 51, 51));
        AddBtnTour.setText("Thêm mới");
        AddBtnTour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddBtnTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnTourActionPerformed(evt);
            }
        });

        EditTourBtn.setBackground(new java.awt.Color(153, 153, 0));
        EditTourBtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EditTourBtn.setText("Sửa thông tin");
        EditTourBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        EditTourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTourBtnActionPerformed(evt);
            }
        });

        DeleteBtnTour.setBackground(new java.awt.Color(255, 102, 102));
        DeleteBtnTour.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DeleteBtnTour.setText("Xóa");
        DeleteBtnTour.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        DeleteBtnTour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnTourActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 153, 153), 2));

        jButton2.setText("Trang chủ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        IndexBtn.setText("Quay lại");
        IndexBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IndexBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(IndexBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(IndexBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tên tour:");

        txtSearchString.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        searchBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        searchBtn.setText("Tìm kiếm");
        searchBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSearchString, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(searchBtn)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearchString)
                    .addComponent(searchBtn))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sắp sếp theo: ");

        SortComboBox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        SortComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giá tiền tăng", "Giá tiền giảm"}));
        SortComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortComboBoxActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SortComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(102, 102, 102)
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(AddBtnTour)
                        .addGap(110, 110, 110)
                        .addComponent(EditTourBtn)
                        .addGap(87, 87, 87)
                        .addComponent(DeleteBtnTour, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AddBtnTour)
                            .addComponent(EditTourBtn)
                            .addComponent(DeleteBtnTour))
                        .addGap(71, 71, 71))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public Tour getElementAt(int index) {
            Iterator<Tour> it = dsTour.iterator();
            int currentIndex = 0;
            while (it.hasNext()) {
                Tour new_t = it.next();
                if (currentIndex == index) {
                    return new_t;
                }
                currentIndex++;
            }
            return null;
        }
    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        LinkedHashSet<Tour> list = new LinkedHashSet<>();
        String searchString = txtSearchString.getText().trim();
        if(searchString.isEmpty()){
            JOptionPane.showMessageDialog(this, 
                    "Chưa nhập thông tin tìm kiếm","Thông báo", WIDTH);
        }
        else{
            list = QuanLyTourController.SearchTours(dsTour, searchString);
            if(list.isEmpty()){
                JOptionPane.showMessageDialog(rootPane, "Không tìm thấy tour!");
            }
            else{
                this.loadTableTourBySearchString(list);
            }
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void SortComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortComboBoxActionPerformed
       int index = SortComboBox.getSelectedIndex();
       QuanLyTourController.sortByPrice(dsTour, index);
       loadTableTourBySortString();
    }//GEN-LAST:event_SortComboBoxActionPerformed

    private void EditTourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTourBtnActionPerformed
        Tour editTour = new Tour();
        dongChon = TourTable.getSelectedRow();
        if(dongChon != -1){
            editTour = this.getElementAt(dongChon);
            EditTourForm editForm = new EditTourForm(this, rootPaneCheckingEnabled, editTour);
            editForm.setVisible(true);
        }
        else{
            JOptionPane.showMessageDialog(this, 
                    "Chưa chọn dòng nào","Thông báo", WIDTH);
        }
    }//GEN-LAST:event_EditTourBtnActionPerformed

    private void AddBtnTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnTourActionPerformed
        CreateForm createForm = new CreateForm(this, rootPaneCheckingEnabled);
        createForm.setVisible(true);
    }//GEN-LAST:event_AddBtnTourActionPerformed

    private void DeleteBtnTourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnTourActionPerformed
        dongChon = TourTable.getSelectedRow();
        if(dongChon != -1){
            int confirm = JOptionPane.showConfirmDialog(
                    rootPane,
                    "Bạn có chắc chắn muốn xóa?",
                    "Xác nhận xóa",
                    JOptionPane.YES_NO_OPTION
            );
            if(confirm == JOptionPane.YES_OPTION){
                    Tour removeTour = this.getElementAt(dongChon);
                    for(DonHang d: dsDH){
                    if(d.getMaTour().equals(removeTour.getMaTour())){
                        dsDH.remove(d);
                        controllerDH.writeToFile(dsDH, "QLDonHang.txt");
                        break;
                    }
                }
                dsTour.remove(removeTour);
                QuanLyTourController.writeToFile(dsTour, "Tour_List.txt");
                loadTableTour();
            }
        }
        else if(dsTour.isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "Không có dữ liệu trong bảng!");
        }
        else{
            JOptionPane.showMessageDialog(this, 
                    "Chưa chọn dòng xóa","Thông báo", WIDTH);
        }
    }//GEN-LAST:event_DeleteBtnTourActionPerformed

    private void IndexBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IndexBtnActionPerformed
        this.loadTableTour();
        txtSearchString.setText("");
        SortComboBox.setSelectedIndex(0);
    }//GEN-LAST:event_IndexBtnActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
            this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyTour.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            new QuanLyTour().setVisible(true);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    //
    public void addTour(Tour new_t){
        try{
            dsTour.add(new_t);
            QuanLyTourController.writeToFile(dsTour, "Tour_List.txt");
            loadTableTour();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, 
                    "Lỗi không ghi ghi được file","Thông báo", WIDTH);
        }
    }
    public void EditTour(Tour new_t){
        try{
            String id = new_t.getMaTour();
            Tour editTour = new Tour();
            for(Tour i : dsTour){
                if(i.getMaTour().contains(id)){
                    editTour = i;
                    break;
                }
            }
            editTour.setTenTour(new_t.getTenTour());
            editTour.setGiaTien(new_t.getGiaTien());
            editTour.setDiaDiem(new_t.getDiaDiem());
            editTour.setDanhGia(new_t.getDanhGia());
            editTour.setLichTrinh(new_t.getLichTrinh());
            //
            for(DonHang d: dsDH){
                if(d.getMaTour().contains(editTour.getMaTour())){
                    d.setTour(editTour);
                    controllerDH.writeToFile(dsDH, "QLDonHang.txt");
                    break;
                }
            }
            QuanLyTourController.writeToFile(dsTour, "Tour_List.txt");
            loadTableTour();
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this, 
                    "Lỗi không ghi ghi được file","Thông báo", WIDTH);
        }
    }
    private void setTableAlignmentCenter(javax.swing.JTable table) {
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.LEFT);
        
        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }
    }
    private void setTableHeaderAlignmentCenter(javax.swing.JTable table) {
        DefaultTableCellRenderer headerRenderer = (DefaultTableCellRenderer) table.getTableHeader().getDefaultRenderer();
        headerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        table.getTableHeader().setDefaultRenderer(headerRenderer);
        table.getTableHeader().setFont(table.getTableHeader().getFont().deriveFont(java.awt.Font.BOLD));
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtnTour;
    private javax.swing.JButton DeleteBtnTour;
    private javax.swing.JButton EditTourBtn;
    private javax.swing.JButton IndexBtn;
    private javax.swing.JComboBox<String> SortComboBox;
    private javax.swing.JTable TourTable;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField txtSearchString;
    // End of variables declaration//GEN-END:variables
}
